services:
  image-service:
    container_name: image-service
    build: .
    ports:
      - "${IMAGE_SERVICE_PORT:-3100}:3100"
    restart: always
    env_file:
      - .env
    environment:
      - PORT=3100
    volumes:
      - ./data/images:${LOCAL_STORAGE_PATH:-/data/images}
